title: Streamdata Discover - Developer
url: discover.developer.streamdata.io
tag: Discover
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]

github_user: streamdata-products
github_repo: discover-developer
github_branch: master
